"""agianr

Revision ID: 73773c2ef5d4
Revises: 00de4d2e7109
Create Date: 2025-08-31 14:19:02.955181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73773c2ef5d4'
down_revision = '00de4d2e7109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=24),
               existing_nullable=True)

    # ### end Alembic commands ###
